# Generated by Django 3.0.7 on 2020-06-21 13:23

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('site2', '0002_auto_20200611_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='public_status',
            field=models.BooleanField(choices=[('1', '公開'), ('2', '非公開')], default=True, verbose_name='公開/非公開'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=mdeditor.fields.MDTextField(max_length=500, verbose_name='記事内容'),
        ),
    ]
