# Generated by Django 3.0.7 on 2020-06-23 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site2', '0004_recruitlong_recruitshort'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitlong',
            name='public_status',
            field=models.BooleanField(default=False, verbose_name='公開・非公開'),
        ),
        migrations.AddField(
            model_name='recruitshort',
            name='public_status',
            field=models.BooleanField(default=False, verbose_name='公開・非公開'),
        ),
    ]
