# Generated by Django 3.0.7 on 2020-06-23 02:45

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('site2', '0006_auto_20200623_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruit',
            name='discription',
            field=mdeditor.fields.MDTextField(max_length=500, verbose_name='記事内容'),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='long_short',
            field=models.BooleanField(default=False, verbose_name='チェックで短期'),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='public_status',
            field=models.BooleanField(default=False, verbose_name='チェックで公開'),
        ),
    ]
