# Generated by Django 3.0.7 on 2020-06-25 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site2', '0007_auto_20200623_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='public_status',
            field=models.BooleanField(choices=[('1', '公開'), ('2', '非公開')], default=False, verbose_name='公開/非公開'),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='public_status',
            field=models.BooleanField(verbose_name='チェックで公開'),
        ),
    ]
